name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:

  call-workflow:

    uses: rsy2022p/central/.github/workflows/test.yml@main

    with:
      app-name: appteam

    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
